[package]
distribution = "2201.7.0"
org = "ballerinax"
name = "googleapis.drive"
version = "@toml.version@"
authors = ["Ballerina"]
repository = "https://github.com/ballerina-platform/module-ballerinax-googleapis.drive"
keywords = ["Drive", "Cost/Free", "Vendor/Google"]
icon = "icon.png"
license = ["Apache-2.0"]

[build-options]
observabilityIncluded = true
