name: GraalVM Check

on:
  schedule:
    - cron: '30 18 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v3

      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          version: 'latest'
          java-version: '17'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check GraalVM installation
        run: |
          echo "GRAALVM_HOME: ${{ env.GRAALVM_HOME }}"
          echo "JAVA_HOME: ${{ env.JAVA_HOME }}"
          native-image --version

      - name: Build Using GraalVM
        run: ./gradlew build -P balGraalVMTest
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
